# Generated by Django 4.2.30 on 2026-07-12 17:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('listing_type', models.CharField(choices=[('sofa', 'Sofa'), ('spare_room', 'Spare Room'), ('floor_space', 'Floor Space / Blow-up Bed'), ('garage', 'Garage / Rehearsal Space')], max_length=20)),
                ('description', models.TextField()),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('town_city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, default=10.0, max_digits=6, validators=[django.core.validators.MinValueValidator(10.0)])),
                ('max_guests', models.PositiveIntegerField(default=1)),
                ('max_nights', models.PositiveIntegerField(default=7, help_text='Maximum consecutive nights')),
                ('includes_breakfast', models.BooleanField(default=True, help_text='Tea/coffee and toast minimum')),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('allows_instruments', models.BooleanField(default=False)),
                ('is_pet_friendly', models.BooleanField(default=False)),
                ('has_shower', models.BooleanField(default=False)),
                ('house_rules', models.TextField(blank=True)),
                ('noise_curfew', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
